language: ruby
cache: bundler
rvm:
  - 2.4.1
services:
  - postgresql
  - memcached
  - redis-server
addons:
  postgresql: "9.6"
  ssh_known_hosts: git@git.handsontable.com
before_install:
  - openssl aes-256-cbc -K $encrypted_daa687493782_key -iv $encrypted_daa687493782_iv -in ci/frc_rsa.enc -out ~/.ssh/frc_rsa -d
script:
  - RAILS_ENV=test bundle exec rake assets:precompile
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rspec
  - RAILS_ENV=test bundle exec rake test
before_script:
  - psql -c 'create database drfvote_test;' -U postgres
