# Global config

default:
  ignore: true
  name: boston
  lists:
    - application
    - allocated
    - ice_box
    - scheduled
    - pre_funded
    - passed
    - rejected

# Define teams below

boston: &boston
  listserv: 'iteambos'
  channel: 'iteambos'
  boards:
    - '6hD5AVNy'
    - '6880SewW'
  snapshots:
    - '0B2FgZYzHz3i9fk1Zbnl1SEluNEltVEljU251dEdlb2dDb0FtcFpKQy1PNVJvZHR4NlVrWlU'
    - '0B05wlJAiP95LSHR1MzB4eTdZX0k'
  excludes:
    - '0BzqJUvAXolWLVndIbG4ySFNYR0U'
  prevote_discussions: '0B5YV7AKNT7yoU1lDUWI5ajRON1U'
  coffee_chats: '0B5YV7AKNT7yoRW4yS19EWFhtYXc'
  lists:
    application: 'Applied at Website'
    allocated: 'Stage 1: Top of Funnel'
    ice_box: 'Not Seeking Funding Right Now'
    scheduled: 'Scheduled to Pitch'
    pre_funded: 'Invested'
    funded:
      - 'Invested'
      - 'Administered Note'
      - 'Funded'
    passed: 'Post-pitch (Stage 4)'
    rejected: 'Passed - No Pitch'
  time_zone: 'Eastern Time (US & Canada)'

nyc:
  ignore: <%= !Rails.env.production? %>
  listserv: 'iteamnyc'
  channel: 'iteamnyc'
  boards:
    - 'WtHewJmA'
  snapshots:
    - '0B40v9HWp1QGqZFlKTUsxTGpYbFk'
    - '0B40v9HWp1QGqMnlCLXVxYUswa00'
    - '0BxwhX9OPjSH_M0ozSGZKRzVMV1k'
    - '0BxwhX9OPjSH_blpueVNpVlIzZHc'
  prevote_discussions: '0B5YV7AKNT7yocjBRa3NrdmtQWk0'
  coffee_chats: '0B5YV7AKNT7yoZW9MUC1nTktyeEU'
  lists:
    application: 'Applied at Website'
    allocated: 'Allocated Point Partner'
    ice_box: 'Waiting for more progress'
    scheduled: 'Scheduled to Pitch'
    pre_funded: 'Invested'
    funded:
      - 'Invested'
      - 'Shutdown'
    passed: 'Passed - Pitched'
    rejected: 'Passed - No Pitch'
  time_zone: 'Eastern Time (US & Canada)'

sf:
  ignore: <%= !Rails.env.production? %>
  listserv: 'iteamsfbay'
  channel: 'iteamsf'
  boards:
    - 'lSsw6XnH'
  snapshots:
    - '0B5YV7AKNT7yoT1QycnluOHJFd0k'
  prevote_discussions: '0B5YV7AKNT7yoVmoxT1VsaHdiLUk'
  coffee_chats: '0B5YV7AKNT7yoVFRjdDlvNXdZTnM'
  lists:
    application: 'Applied at Website'
    allocated: 'Allocated Point Partner'
    ice_box: 'Hold'
    scheduled: 'Scheduled to Pitch'
    pre_funded: 'Yes - Money not yet wired'
    funded:
        - 'Yes - Money not yet wired'
        - 'Invested - Active'
        - 'Invested - Dissolved'
        - 'Invested - Exited'
        - 'Inactive deals'
    passed: 'Passed - Pitched'
    rejected: 'Passed - No Pitch'
  time_zone: 'Pacific Time (US & Canada)'

phl:
  ignore: <%= !Rails.env.production? %>
  listserv: 'iteamphl'
  channel: 'philly-iteam'
  boards:
    - 'GSYLWzGT'
  snapshots:
    - '0B8PQ_6u1wbLuS1AxeFA4TkdXQmM'
    - '0B8PQ_6u1wbLuTEFUV2hBRmROQzA'
    - '0B5YV7AKNT7yoVlNER3dscVZPdk0'
    - '0B8PQ_6u1wbLudXVOaERXcXN0cFE'
  prevote_discussions: '0B5YV7AKNT7yoUGNhYXlfa182MUU'
  coffee_chats: '0B5YV7AKNT7yoMWtQMkVzZ3Vvb2s'
  lists:
    application: 'Applied at Website'
    allocated: 'Allocated Point Partner'
    ice_box: 'Deferred / Check-In Later'
    scheduled: 'Pitching'
    pre_funded: 'Invested'
    funded:
      - 'Invested'
      - 'Exited'
      - 'Returned at Par'
      - 'Shut Down'
    passed: 'Passed - Pitched'
    rejected: 'Passed - No Pitch'
  time_zone: 'Eastern Time (US & Canada)'

test:
  <<: *boston
  ignore: <%= !Rails.env.development? %>
  channel: 'bot_tests'
  listserv: 'ym'
